inline documentation adjusted

diff --git a/tonuino-sdcard b/tonuino-sdcard
--- a/tonuino-sdcard
+++ b/tonuino-sdcard
@@ -1,13 +1,13 @@
 #!/bin/bash
 ##############################################################################
 #
-# DESC: manage TonUINO sdcard
+# DESC: manage TonUINO sdcard content, based on ID3v2 tags (if available)
 #
 # INFO: https://www.voss.earth/tonuino/, Struktur auf der SD-Karte
 #
 # DEPS: depends on id3v2 tool/command
 #
-# VERS: v1.1 - 20190121 - Michi
+# VERS: v1.11 - 20190122 - Michi
 #
 ##############################################################################
 
@@ -19,9 +19,9 @@ function usage {
   echo "Usage: $(basename "$0") [-h] || [-v] -l <path to sdcard> || [-v] [-n] [-r] -c <music folder> <path to sdcard> || -R <path to sdcard>" >&2
   echo -e "\t-h|--help      show help/usage" >&2
   echo -e "\t-v|--verbose   show detailed information about executed commands" >&2
-  echo -e "\t-l|--list      list content of sdcard based on ID3v2 tags" >&2
+  echo -e "\t-l|--list      list content of sdcard based on ID3v2 tags (if available)" >&2
   echo -e "\t-c|--copy      copy content of music folder to sdcard, reflecting folder structure and naming convention" >&2
-  echo -e "\t-n|--num       enumerate files mannually (e.g. in case of missing ID3v2 tags or mixed files" >&2
+  echo -e "\t-n|--num       enumerate files mannually (e.g. in case of missing ID3v2 tags or mixed files)" >&2
   echo -e "\t-r|--replace   replace already existing destination folder" >&2
   echo -e "\t-R|--reorder   reorder sdcard folders to eliminate gaps" >&2
   exit 1
@@ -33,7 +33,9 @@ function copy {
   [ ! -d "$SRC" ] || [ -z "$(find "$SRC" -type f -iname \*.mp3 2>/dev/null)" ] && { echo "ERROR: please specify a valid path to your MP3 files!" >&2; exit 1; }
   [ ! -d "$DST" ] && { echo "ERROR: please specify a valid path to your sdcard!" >&2; exit 1; }
 
+  # clear existing directory, which has to be replaced OR create a new/empty directory
   if [[ -n "$REPL" ]]; then
+    # try to clear existing directory, set destination path and directory accordingly
     rm "$DST"/*.mp3  >/dev/null 2>&1 || { echo "ERROR: can't clean existing directory $DST" >&2; exit 1; }
     DN="$(basename "$DST")"
     DST="$(dirname "$DST")"
@@ -59,7 +61,7 @@ function copy {
     cp "$FILE" "$DST"/"$DN"/"$FN" >/dev/null 2>&1 || { echo "ERROR: can't copy file $FILE to $DST/$DN/$FN" >&2; exit 1; }
     # be verbose
     [[ -n $VERB ]] && echo "DONE"
-    # increase dediacted counter
+    # increase counter
     ((CNT++))
   done
 
@@ -74,7 +76,7 @@ function list {
   # loop over all sdcard folders
   for DIR in $(find "$SRC" -type d -name "[0-9][0-9]" | sort -n); do
     # in verbose mode print detailed information for each file (artists, album, title if ID3 tags are available)
-    # or a summary per folder (artist, album if ID3 tags are available) otherwise
+    # or a summary for each folder (artist, album if ID3 tags are available) otherwise
 		if [[ -n $VERB ]]; then
       # print directory name
 			echo "$DIR"
@@ -101,7 +103,7 @@ function list {
         ID3+=("$LINE")
       done < <(id3v2 -l "$DIR"/*.mp3 | LC_ALL=C sed -ne '/TPE1/s/.*: \(.*\)/1Artist: \1/p;/TALB/s/.*: \(.*\)/2Album: \1/p;s/.*\(No ID3.* tag\)/3\1/p' | \
         LC_ALL=C sort -n | LC_ALL=C uniq | LC_ALL=C cut -c2-)
-      # if array holds exactly 2 elements, it has to be artist and album information, so print it out
+      # if array holds exactly 2 elements, it has to be artist and album information
       # if array holds more than 2 elements, the directory contains songs of various artists and/or albums
       # otherwise no ID3 tags were found
       if [[ ${#ID3[*]} -eq "2" ]]; then
@@ -117,7 +119,7 @@ function list {
   exit 0
 }
 
-# reorder sdcard folders to eliminate gaps
+# reorder sdcard folders to eliminate gaps (may not be very useful, because RFID cards/tags have to be reconfigured accordingly)
 function reorder {
   # validate source (sdcard mount point, containing MP3 files)
   [ ! -d "$SRC" ] || [ -z "$(find "$SRC" -type f -iname \*.mp3 2>/dev/null)" ] || [ -z "$(find "$SRC" -type d -name "[0-9][0-9]" 2>/dev/null)" ] && { echo "ERROR: please specify a valid path to your sdcard!" >&2; exit 1; }
@@ -127,7 +129,7 @@ function reorder {
     DIRS+=( "$(basename "$LINE")" )
   done < <(find "$SRC" -type d -name "[0-9][0-9]" 2>/dev/null | LC_ALL=C sort -n)
 
-  # exit function incase of no enumeration gap
+  # exit function in case there's no gap (directories are available and number of dirs equals last dirs name)
   [[ "${#DIRS[*]}" -gt 0 ]] && [[ "${#DIRS[*]}" -eq "${DIRS[$((${#DIRS[*]}-1))]}" ]] && { echo "INFO: nothing to do"; exit 0; }
 
   # enumeration counter
