FIX: made the script more robust FIX: append mode now honors ID3v2 track numbers and therefore doesn't imply manual enumeration

diff --git a/tonuino-sdcard b/tonuino-sdcard
--- a/tonuino-sdcard
+++ b/tonuino-sdcard
@@ -8,7 +8,7 @@
 #
 # DEPS: depends on id3v2 tool/command
 #
-# VERS: v1.2 - 20190125 - Michi
+# VERS: v1.3 - 20190126 - Michi
 #
 ##############################################################################
 
@@ -23,17 +23,26 @@ function usage {
   echo -e "\t-l|--list      list content of sdcard based on ID3v2 tags (if available)" >&2
   echo -e "\t-c|--copy      copy content of music folder to sdcard, reflecting folder structure and naming convention" >&2
   echo -e "\t-n|--num       enumerate files mannually (e.g. in case of missing ID3v2 tags or mixed files)" >&2
-  echo -e "\t-a|--add       add files to an existing folder (implies parameter -n, enumerate files mannually)" >&2
+  echo -e "\t-a|--add       add files to an existing folder" >&2
   echo -e "\t-r|--replace   replace already existing destination folder" >&2
   echo -e "\t-R|--reorder   reorder sdcard folders to eliminate gaps" >&2
   exit 1
 }
 
 # copy content of music folder to sdcard, reflecting folder structure and naming convention
-function copy {
+copy() {
   # validate source (directory, containing MP3 files) and destination (sdcard mount point)
   [ ! -d "$SRC" ] || [ -z "$(find "$SRC" -type f -iname \*.mp3 2>/dev/null)" ] && { echo "ERROR: please specify a valid path to your MP3 files!" >&2; exit 1; }
   [ ! -d "$DST" ] && { echo "ERROR: please specify a valid path to your sdcard!" >&2; exit 1; }
+  # verify destination is either root or subfolder, depending on copy mode (initial, append, replace)
+  re='.*[0-9][0-9]/*$'
+  if [ -n "$REPL" ] || [ -n "$ADD" ] && [[ ! $DST =~ $re ]]; then
+    echo "ERROR: please specify a valid folder on your sdcard!" >&2
+    exit 1
+  elif [ -z "$REPL" ] && [ -z "$ADD" ] && [[ $DST =~ $re ]]; then
+    echo "ERROR: please don't specify subfolders, just sdcard root..." >&2
+    exit 1
+  fi
 
   # variable used for manual enumeration of files or files without ID3 tags
   CNT=1
@@ -61,9 +70,20 @@ function copy {
   while IFS= read -d $'\0' -r FILE ; do
     # try to get a valid track number and eliminate left hand zeros
     # https://stackoverflow.com/questions/8078167/bizarre-issue-with-printf-in-bash-script09-and-08-are-invalid-numbers-07/11804275
-    FN="$(printf "%03d" "$(( 10#$(id3v2 -l "$FILE" | LC_ALL=C sed -ne '/TRCK/s/.*:[^0-9]*\([0-9]*\).*/\1/p') ))").mp3"
-    # use dedicated counter for filenames if the above command didn't succeed or manual enumeration has been forced (-n)
-    [ "$FN" = 000.mp3 ] || [ -n "$ENUM" ] && FN="$(printf "%03d" "$CNT").mp3"
+    FN=$(( 10#$(id3v2 -l "$FILE" | LC_ALL=C sed -ne '/TRCK/s/.*:[^0-9]*\([0-9]*\).*/\1/p') ))
+
+    # use dedicated counter for file number if the above command didn't succeed or manual enumeration has been forced (-n);
+    # add enumeration overhead to file number in append mode
+    if [ "$FN" -eq 0 ] || [ -n "$ENUM" ]; then
+      FN=$CNT
+      ((CNT++))
+    elif [ -n "$ADD" ]; then
+      ((FN+=CNT))
+    fi
+
+    # set file name accordingly
+    FN="$(printf "%03d" "$FN").mp3"
+
     # be verbose
     [ -n "$VERB" ] && echo -n "cp $FILE $DST/$DN/$FN ... "
     # try to copy file
@@ -71,14 +91,13 @@ function copy {
     # be verbose
     [ -n "$VERB" ] && echo "DONE"
     # increase counter
-    ((CNT++))
   done < <(find "$SRC" -type f -iname \*.mp3 -print0 2>/dev/null)
 
   exit 0
 }
 
 # list content of sdcard based on ID3v2 tags, if available
-function list {
+list() {
   # validate source (sdcard mount point, directory structure, mp3 files)
   [ ! -d "$SRC" ] && { echo "ERROR: please specify a valid path to your sdcard!" >&2; exit 1; }
   [ -z "$(find "$SRC" -type f -iname \*.mp3 2>/dev/null)" ] || [ -z "$(find "$SRC" -type d -name "[0-9][0-9]" 2>/dev/null)" ] && { echo "INFO: $SRC seems to be empty..." >&2; exit 1; }
@@ -130,7 +149,7 @@ function list {
 }
 
 # reorder sdcard folders to eliminate gaps (may not be very useful, because RFID cards/tags have to be reconfigured accordingly)
-function reorder {
+reorder() {
   # validate source (sdcard mount point, directory structure, mp3 files)
   [ ! -d "$SRC" ] && { echo "ERROR: please specify a valid path to your sdcard!" >&2; exit 1; }
   [ -z "$(find "$SRC" -type f -iname \*.mp3 2>/dev/null)" ] || [ -z "$(find "$SRC" -type d -name "[0-9][0-9]" 2>/dev/null)" ] && { echo "INFO: $SRC seems to be empty, so there's nothing to reorder..." >&2; exit 1; }
@@ -163,7 +182,7 @@ while [ "$#" -gt 0 ]; do
   case "$1" in
     -v|--verbose) VERB=1;;
     -r|--replace) REPL=1;;
-    -a|--add) ADD=1; ENUM=1;;
+    -a|--add) ADD=1;;
     -n|--num) ENUM=1;;
     -R|--reorder) CMD="reorder"; SRC="$2"; shift;;
     -l|--list) CMD="list"; SRC="$2"; shift;;
